# Kamyab Jawan Program
### Name: Umer Farooq
### Date: 28/03/2022
### Batch: 3
### Trade: Artificial Intelligence
### Teachers: Mr. Najam Aziz, Mr. Sikandar Hayat
### Work: Assignment 3 for Numpy

In [1]:
import warnings
warnings.filterwarnings('ignore')

1. Import numpy as `np` and print the version number.

In [2]:
import numpy as np
print("Numpy Version: ",np.__version__)

Numpy Version:  1.20.3


2. Create a 1D array of numbers from 0 to 9 Desired output:
#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#a = np.array(range(10), dtype=np.int8)
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=np.int8)
print(a)

type(a)

[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

3. Create a 3×3 numpy array of all True’s

In [15]:
a_all_true = np.ones((3,3), dtype=bool)
print(a_all_true)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


4. Extract all odd numbers from arr Input:

In [4]:
arr = np.array(range(10), dtype=np.int8)
print(arr)

# Get all odd numbers
odd_numbers = arr[[arr % 2 != 0]]
# arr[[arr % 2 != 0]] here each element of arr is checked if it is odd or not and if it is odd then it is added to the new array. 
# [[arr % 2 != 0]] is the same as for i in range(len(arr)): if arr[i] % 2 != 0: odd_numbers.append(arr[i]). 
# In arr[[]], the double brackets are used to specify the indices of the array for which the condition is to be checked.
print(odd_numbers)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


numpy.ndarray

5. Replace all odd numbers in arr with -1 Input:

In [21]:
for i in range(len(arr)):
    if arr[i] % 2 != 0:
        arr[i] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


6. Replace all odd numbers in arr with -1 without changing arr Input

In [10]:
input_arr = np.array(range(10), dtype=np.int8)
print("Input Array is: ",input_arr)
odd_num_array = np.array([], dtype=np.int8)
for i in range(len(input_arr)):
    if input_arr[i] % 2 != 0:
        odd_num_array = np.append(odd_num_array, -1)
    else:
        odd_num_array = np.append(odd_num_array, input_arr[i])
print("Output Array is: ",odd_num_array)

Input Array is:  [0 1 2 3 4 5 6 7 8 9]
Output Array is:  [ 0 -1  2 -1  4 -1  6 -1  8 -1]


7. Convert a 1D array to a 2D array with 2 rows Input:

In [17]:
a_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=np.int8)
print(a_1d)
new_2d = a_1d.reshape(2,5) # 2 rows and 5 columns
print(new_2d)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


8. Stack arrays a and b vertically. 

* vstack is used to stack arrays vertically.
* hstack is used to stack arrays horizontally.

In [9]:
def stack_arrays(arr1, arr2):
    return np.vstack((arr1, arr2))

a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
print(stack_arrays(a, b))


[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


9. Stack arrays a and b horizontally. 

In [10]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)

harry = np.hstack((a, b))
print(harry)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
